name: Badges

on:
    workflow_call:
    workflow_dispatch:

permissions:
    contents: write

jobs:
    generate-badges:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: 📝 Generate badges
              uses: actions/github-script@v6
              with:
                  script: |
                      const p = require("path");
                      const fs = require("fs/promises");
                      const { data: releases } = await github.rest.repos.listReleases({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                      });
                      const latest = releases.find(x => !x.draft && !x.prerelease);
                      const outputDir = p.join(process.cwd(), "dist-badges");
                      await fs.mkdir(outputDir, { recursive: true });
                      await fs.writeFile(p.join(outputDir, "badge-latest.json"), JSON.stringify({
                          schemaVersion: 1,
                          label: "latest",
                          message: latest?.tag_name ?? "unknown",
                          color: "blue",
                      }));

            - name: 🚀 Push badges
              run: |
                  git config user.name "[actions] generate-badges"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git checkout --orphan dist-badges
                  git rm -rf . >/dev/null 2>&1 || true
                  git add dist-badges/
                  git commit -m "Update badges" || git commit --allow-empty -m "Update badges"
                  git push origin HEAD:dist-badges --force